# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Solutions
author: imcb
email: irismessage@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://irises.me" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://irismessage.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
    # - jekyll-category-pages

category_descs:
    solutions: The namesake of the website. When I can't find a solution to a problem on the web, I'll post it here, like one-sided stackoverflow. <https://xkcd.com/979/>
    assets: Random assets I want to share, like github gists but for miscellaneous .psd files.
    releases: A digestible feed of projects I'm working on that I want to share, so you don't have to trawl through my repositories and commits etc.
    blog: uncategorised posts are just general blog posts.
category_path: category

banner:
    src: "/assets/images/gaming-ready-pcs.jpg"
    alt: REAL

# https://github.com/jekyll/jekyll-seo-tag
locale: en_GB

# https://github.com/jekyll/minima/tree/2.5-stable#change-default-date-format
minima:
    date_format: "%Y-%m-%d"

# https://github.com/jekyll/minima/tree/2.5-stable#social-networks
github_username: irismessage
youtube_username: Sgp10
gitlab:
 - username: irismessage
   instance: gitlab.com


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
